export { default as Home } from './Home'
export { default as Article } from './Article'
export { default as EditorPage } from './Editor'
export { default as Profile } from './Profile'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Bookmarks } from './Bookmarks'
export { default as NotFound } from './NotFound'
